-- Legacy pre-Alembic NOVA schema required by the first migrations.
--
-- The first Alembic revision assumes these two tables already exist.
-- This file recreates that historical baseline only for disposable CI
-- databases so the real migration chain can be exercised from a clean DB.

CREATE TABLE IF NOT EXISTS messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS memories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    memory_text TEXT NOT NULL,
    category VARCHAR(50) NOT NULL,
    importance VARCHAR(20) NOT NULL
        DEFAULT 'medium',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
